import type { Venue } from "@/types/recommendation";

/**
 * 직접 큐레이션한 시드 데이터 (MVP). 실 리뷰·조회수 API 연동은 이 feature 범위 밖.
 * 지역별 개수를 의도적으로 다르게 뒀다 — 동탄역은 전 구간이 다소 고가라 저예산
 * 입력 시 "예산 초과뿐" 케이스를, 오산운암은 3곳뿐이라 "시드 부족" 케이스를 실데이터로 재현한다.
 */
const VENUES: Venue[] = [
  {
    id: "osan-charcoal",
    name: "숯불향 오산역점",
    category: "고깃집",
    region: "오산역",
    rating: 4.6,
    reviewCount: 1204,
    viewCount: 8900,
    pricePerPerson: 28000,
  },
  {
    id: "osan-izakaya",
    name: "이자카야 온기 오산",
    category: "이자카야",
    region: "오산역",
    rating: 4.5,
    reviewCount: 902,
    viewCount: 6200,
    pricePerPerson: 29500,
  },
  {
    id: "osan-samgyup",
    name: "모던삼겹 오산",
    category: "고깃집",
    region: "오산역",
    rating: 4.4,
    reviewCount: 731,
    viewCount: 5100,
    pricePerPerson: 27000,
  },
  {
    id: "osan-omakase",
    name: "오마카세 결 오산",
    category: "일식",
    region: "오산역",
    rating: 4.8,
    reviewCount: 540,
    viewCount: 4400,
    pricePerPerson: 42000,
  },
  {
    id: "osan-hof",
    name: "호프집 오산불빛",
    category: "호프",
    region: "오산역",
    rating: 4.3,
    reviewCount: 615,
    viewCount: 3800,
    pricePerPerson: 22000,
  },
  {
    id: "osanunam-gopchang",
    name: "오산운암 곱창골목",
    category: "곱창",
    region: "오산운암",
    rating: 4.5,
    reviewCount: 388,
    viewCount: 2600,
    pricePerPerson: 19000,
  },
  {
    id: "osanunam-samgyup",
    name: "오산운암 삼겹살",
    category: "고깃집",
    region: "오산운암",
    rating: 4.3,
    reviewCount: 512,
    viewCount: 3100,
    pricePerPerson: 21000,
  },
  {
    id: "osanunam-pocha",
    name: "운암포차",
    category: "호프",
    region: "오산운암",
    rating: 4.1,
    reviewCount: 297,
    viewCount: 1900,
    pricePerPerson: 18000,
  },
  {
    id: "dongtan-sushi",
    name: "스시엔 동탄",
    category: "일식",
    region: "동탄역",
    rating: 4.5,
    reviewCount: 480,
    viewCount: 4100,
    pricePerPerson: 22000,
  },
  {
    id: "dongtan-hanwoo",
    name: "한우마당 동탄",
    category: "고깃집",
    region: "동탄역",
    rating: 4.7,
    reviewCount: 690,
    viewCount: 5300,
    pricePerPerson: 35000,
  },
  {
    id: "dongtan-bistro",
    name: "비스트로 동탄",
    category: "양식",
    region: "동탄역",
    rating: 4.4,
    reviewCount: 320,
    viewCount: 2800,
    pricePerPerson: 38000,
  },
  {
    id: "dongtan-izakaya",
    name: "동탄 이자카야 결",
    category: "이자카야",
    region: "동탄역",
    rating: 4.3,
    reviewCount: 410,
    viewCount: 3300,
    pricePerPerson: 26000,
  },
  {
    id: "dongtan-hof",
    name: "동탄 호프거리",
    category: "호프",
    region: "동탄역",
    rating: 4.2,
    reviewCount: 275,
    viewCount: 2100,
    pricePerPerson: 24000,
  },
  {
    id: "dongtanlake-seafood",
    name: "동탄호수 해물찜",
    category: "해물",
    region: "동탄호수",
    rating: 4.6,
    reviewCount: 560,
    viewCount: 4300,
    pricePerPerson: 31000,
  },
  {
    id: "dongtanlake-hanwoo",
    name: "호수뷰 한우",
    category: "고깃집",
    region: "동탄호수",
    rating: 4.7,
    reviewCount: 402,
    viewCount: 3700,
    pricePerPerson: 39000,
  },
  {
    id: "dongtanlake-izakaya",
    name: "동탄호수 이자카야",
    category: "이자카야",
    region: "동탄호수",
    rating: 4.4,
    reviewCount: 331,
    viewCount: 2900,
    pricePerPerson: 27000,
  },
  {
    id: "dongtanlake-hof",
    name: "호수공원 호프",
    category: "호프",
    region: "동탄호수",
    rating: 4.2,
    reviewCount: 218,
    viewCount: 1800,
    pricePerPerson: 21000,
  },
  {
    id: "dongtan1-samgyup",
    name: "동탄1 숯불삼겹",
    category: "고깃집",
    region: "동탄1",
    rating: 4.5,
    reviewCount: 470,
    viewCount: 3600,
    pricePerPerson: 26000,
  },
  {
    id: "dongtan1-jjim",
    name: "동탄1 아구찜",
    category: "찜",
    region: "동탄1",
    rating: 4.4,
    reviewCount: 355,
    viewCount: 2700,
    pricePerPerson: 23000,
  },
  {
    id: "dongtan1-izakaya",
    name: "동탄1 이자카야 봄",
    category: "이자카야",
    region: "동탄1",
    rating: 4.3,
    reviewCount: 289,
    viewCount: 2200,
    pricePerPerson: 25000,
  },
  {
    id: "dongtan1-hof",
    name: "동탄1 호프마을",
    category: "호프",
    region: "동탄1",
    rating: 4.1,
    reviewCount: 190,
    viewCount: 1500,
    pricePerPerson: 19000,
  },
  {
    id: "gangnam-charcoal",
    name: "숯불향 강남점",
    category: "고깃집",
    region: "강남",
    rating: 4.6,
    reviewCount: 1350,
    viewCount: 9600,
    pricePerPerson: 32000,
  },
  {
    id: "gangnam-omakase",
    name: "오마카세 결 강남",
    category: "일식",
    region: "강남",
    rating: 4.9,
    reviewCount: 720,
    viewCount: 6100,
    pricePerPerson: 45000,
  },
  {
    id: "gangnam-izakaya",
    name: "이자카야 온기 강남",
    category: "이자카야",
    region: "강남",
    rating: 4.5,
    reviewCount: 880,
    viewCount: 5400,
    pricePerPerson: 33000,
  },
  {
    id: "gangnam-hof",
    name: "호프집 강남불빛",
    category: "호프",
    region: "강남",
    rating: 4.3,
    reviewCount: 640,
    viewCount: 4200,
    pricePerPerson: 25000,
  },
  {
    id: "gangnam-samgyup",
    name: "모던삼겹 강남",
    category: "고깃집",
    region: "강남",
    rating: 4.4,
    reviewCount: 705,
    viewCount: 4900,
    pricePerPerson: 29000,
  },
];

export const REGIONS: readonly string[] = [
  "오산역",
  "오산운암",
  "동탄역",
  "동탄호수",
  "동탄1",
  "강남",
];

export function getVenuesByRegion(region: string): Venue[] {
  return VENUES.filter((v) => v.region === region);
}

export function getVenuesByIds(ids: string[]): Venue[] {
  const idSet = new Set(ids);
  return VENUES.filter((v) => idSet.has(v.id));
}
